# Generated by Django 4.2.1 on 2023-05-20 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='birth_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passenger',
            name='phone',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
