# Generated by Django 4.2.1 on 2023-05-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_remove_passenger_flights_passenger_flight'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
