# Generated by Django 4.2.1 on 2023-05-20 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_passenger_birth_date_passenger_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookflight',
            name='passenger',
        ),
        migrations.AddField(
            model_name='bookflight',
            name='passenger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flight.passenger'),
            preserve_default=False,
        ),
    ]
