# Generated by Django 4.2.1 on 2023-05-18 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_airport_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
