# Generated by Django 4.2.1 on 2023-05-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_flight_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='remaining_seat',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='total_seat',
            field=models.PositiveSmallIntegerField(default=100),
            preserve_default=False,
        ),
    ]
