# Generated by Django 4.2.1 on 2023-05-20 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0006_passenger_user_alter_airport_is_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='last_name',
        ),
    ]
